version: "3.7"
services:
  app:
    build:
      dockerfile: Dockerfile
    image: docker_laravel
    container_name: docker_laravel
    restart: always
    ports:
      - 9002:80
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - laravel
  db:
    image: mysql
    restart: always
    ports: 
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: bc110317
      MYSQL_DATABASE: kurole
      MYSQL_USER: kurole
      MYSQL_PASSWORD: bc110317
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
